# ESTÁGIO 1: Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copia os arquivos de projeto (.csproj) primeiro para cache de camadas (restore rápido)
COPY ["src/Health.API/Health.API.csproj", "src/Health.API/"]
COPY ["src/Health.Application/Health.Application.csproj", "src/Health.Application/"]
COPY ["src/Health.Domain/Health.Domain.csproj", "src/Health.Domain/"]
COPY ["src/Health.Infrastructure/Health.Infrastructure.csproj", "src/Health.Infrastructure/"]

# Executa o restore das dependências
RUN dotnet restore "src/Health.API/Health.API.csproj"

# Copia todo o restante do código e compila
COPY . .
WORKDIR "/app/src/Health.API"
RUN dotnet build "Health.API.csproj" -c Release -o /app/build

# ESTÁGIO 2: Publish
FROM build AS publish
RUN dotnet publish "Health.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

# ESTÁGIO 3: Final (Runtime)
FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final
WORKDIR /app

# Adiciona suporte a globalização (importante para apps brasileiras: data/moeda)
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

# Cria um usuário não-root por segurança (Best Practice no Kubernetes/Rancher)
USER $APP_UID

COPY --from=publish /app/publish .

# Porta padrão do .NET 8/9 é a 8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "Health.API.dll"]